#!/usr/bin/env bash

readonly CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

get_colorscheme() {
	local option="@tmux-colorscheme"
	local default="dark"

	local colorscheme=$(tmux show-option -gqv "$option")
	if [[ -z "$colorscheme" ]]; then
		echo "$default"
	else
		echo "$colorscheme"
	fi
}

colorscheme=$(get_colorscheme)
tmux source-file "${CURRENT_DIR}/${colorscheme}.tmux"
