#!/usr/bin/env bash

readonly CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

get_background() {
	local option="@gruvbox-background"
	local default="dark"

	local background=$(tmux show-option -gqv "$OPTION")
	if [ -z "$background" ]; then
		echo "$default"
	else
		echo "$background"
	fi
}

background=$(get_background)
tmux source-file "${CURRENT_DIR}/gruvbox-${background}.tmux"
