#!/bin/sh
# get script directory
DOTFILES_DIR=$(readlink -m "${0%/*}")
echo "Global config directory: "\"$DOTFILES_DIR\"""
# prompt user
echo "WARNING: This will destroy any existing config files!"
read -p "Setup global config? (y/n) " ans
case $ans in
	y|Y) ;;
	*) exit;;
esac
# show commands
set -x
# remove default config files/dirs
echo "Removing old config..."
rm $HOME/.vimrc         # rm  vim- config
rm -rf $HOME/.vim       # rm  vim- config directory + plugins
rm -f $HOME/.zshrc      # rm  zsh- config
rm -rf $HOME/.zsh       # rm  zsh- config directory + plugins
rm -f $HOME/.zprofile   # rm  zsh- profile
rm -f $HOME/.tmux.conf  # rm tmux- config
rm -f $HOME/.Xresources # rm  x11- resources
rm -rf $HOME/.i3        # rm   i3- config directory
# symlink global config
echo "Symlinking new config..."
ln -s $DOTFILES_DIR/vim/vimrc $HOME/.vimrc           #  vim- config
ln -s $DOTFILES_DIR/vim $HOME/.vim                   #  vim- config directory
ln -s $DOTFILES_DIR/zsh/zshrc $HOME/.zshrc           #  zsh- config
ln -s $DOTFILES_DIR/zsh $HOME/.zsh                   #  zsh- config directory
ln -s $DOTFILES_DIR/zsh/zprofile $HOME/.zprofile     #  zsh- profile
ln -s $DOTFILES_DIR/tmux/tmux.conf $HOME/.tmux.conf  # tmux- config
ln -s $DOTFILES_DIR/x11/Xresources $HOME/.Xresources #  x11- resources
ln -s $DOTFILES_DIR/i3 $HOME/.i3                     #   i3- config directory
# build command-t (vim plugin)
echo "Compiling command-t (vim plugin)..."
cd $HOME/.vim/bundle/command-t
rake make
cd $DOTFILES_DIR
# install powerline (pip)
cp $DOTFILES_DIR/powerline-config/config.json $DOTFILES_DIR/powerline-config/config.json.bak
cd $DOTFILES_DIR/powerline
pip install --user ./
cd $DOTFILES_DIR
# symlink powerline config
echo "Symlinking powerline config files"
POWERLINE_DIR=$HOME/.local/lib/python2.7/site-packages/powerline
rm -f $POWERLINE_DIR/config_files/config.json $POWERLINE_DIR/config_files/config.json.bak
ln -s $DOTFILES_DIR/powerline-config/config.json $POWERLINE_DIR/config_files/config.json
# powerline vim config
rm -f $POWERLINE_DIR/config_files/themes/vim/custom.json
rm -f $POWERLINE_DIR/config_files/colorschemes/vim/custom.json
ln -s $DOTFILES_DIR/powerline-config/vim_theme.json $POWERLINE_DIR/config_files/themes/vim/custom.json
ln -s $DOTFILES_DIR/powerline-config/vim_colorscheme.json $POWERLINE_DIR/config_files/colorschemes/vim/custom.json
# powerline tmux config
rm -f $POWERLINE_DIR/config_files/themes/tmux/custom.json
rm -f $POWERLINE_DIR/config_files/colorschemes/tmux/custom.json
ln -s $DOTFILES_DIR/powerline-config/tmux_theme.json $POWERLINE_DIR/config_files/themes/tmux/custom.json
ln -s $DOTFILES_DIR/powerline-config/tmux_colorscheme.json $POWERLINE_DIR/config_files/colorschemes/tmux/custom.json
