require('hlslens').setup({ calm_down = true })
vim.keymap.set({ 'n' }, 'n', [[<Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>]], { desc = 'Next search result' })
vim.keymap.set({ 'n' }, 'N', [[<Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>]], { desc = 'Prev search result' })
vim.keymap.set({ 'n' }, '*', [[*<Cmd>lua require('hlslens').start()<CR>]], { desc = 'Search word' })
vim.keymap.set({ 'n' }, '#', [[#<Cmd>lua require('hlslens').start()<CR>]], { desc = 'Search word backwards' })
vim.keymap.set({ 'n' }, 'g*', [[g*<Cmd>lua require('hlslens').start()<CR>]], { desc = 'Search sub-word' })
vim.keymap.set({ 'n' }, 'g#', [[g#<Cmd>lua require('hlslens').start()<CR>]], { desc = 'Search sub-word backwards' })
-- vim-asterisk integration
vim.keymap.set({ 'n', 'v', 'o' }, '*', [[<Plug>(asterisk-z*)<Cmd>lua require('hlslens').start()<CR>]], { desc = 'Search word' })
vim.keymap.set({ 'n', 'v', 'o' }, '#', [[<Plug>(asterisk-z#)<Cmd>lua require('hlslens').start()<CR>]], { desc = 'Search word backwards' })
vim.keymap.set({ 'n', 'v', 'o' }, 'g*', [[<Plug>(asterisk-gz*)<Cmd>lua require('hlslens').start()<CR>]], { desc = 'Search sub-word' })
vim.keymap.set({ 'n', 'v', 'o' }, 'g#', [[<Plug>(asterisk-gz#)<Cmd>lua require('hlslens').start()<CR>]], { desc = 'Search sub-word backwards' })
