set guioptions-=T " remove toolbar
set guioptions-=m " remove menu
set guioptions+=g " grey menu items
set guioptions-=c " hide intro
set guioptions-=i " hide scrollbars
set guioptions-=r " hide scrollbars
set guioptions-=L " hide scrollbars
set guioptions-=l " hide scrollbars

if has('gui_win32')
	set guifont=Hack:h9
else
	set guifont=Hack\ 9
endif

" Toggle menu
nmap <f1> :if &go=~#'m'<Bar>set go-=m<Bar>else<Bar>set go+=m<Bar>endif<cr>
