vim.api.nvim_set_keymap('', '*',   [[ <Plug>(asterisk-*) ]],   {})
vim.api.nvim_set_keymap('', '#',   [[ <Plug>(asterisk-#) ]],   {})
vim.api.nvim_set_keymap('', 'g*',  [[ <Plug>(asterisk-g*) ]],  {})
vim.api.nvim_set_keymap('', 'g#',  [[ <Plug>(asterisk-g#) ]],  {})
vim.api.nvim_set_keymap('', 'z*',  [[ <Plug>(asterisk-z*) ]],  {})
vim.api.nvim_set_keymap('', 'gz*', [[ <Plug>(asterisk-gz*) ]], {})
vim.api.nvim_set_keymap('', 'z#',  [[ <Plug>(asterisk-z#) ]],  {})
vim.api.nvim_set_keymap('', 'gz#', [[ <Plug>(asterisk-gz#) ]], {})
