vim.keymap.set('n', 'Q', '<NOP>', { desc = 'Disable ex-mode mapping' })
vim.keymap.set({ 'n', 'v' }, '<Leader>y', '"+y', { desc = 'Yank to system clipboard' })
vim.keymap.set('n', 'j', 'gj', { desc = 'Next line-wrap' })
vim.keymap.set('n', 'k', 'gk', { desc = 'Previous line-wrap' })
vim.keymap.set('n', 'gj', 'j', { desc = 'Next line' })
vim.keymap.set('n', 'gk', 'k', { desc = 'Previous line' })
vim.keymap.set('x', '>', '>gv', { desc = 'Increase indent' })
vim.keymap.set('x', '<', '<gv', { desc = 'Decrease indent' })
-- terminal movement
vim.keymap.set('t', '<A-i>', function () vim.cmd('buffer #') end)
vim.keymap.set('t', '<C-w>h', [[<C-\><C-n><C-w>h]])
vim.keymap.set('t', '<C-w>j', [[<C-\><C-n><C-w>j]])
vim.keymap.set('t', '<C-w>k', [[<C-\><C-n><C-w>k]])
vim.keymap.set('t', '<C-w>l', [[<C-\><C-n><C-w>l]])
